name: CI Build and Analysis

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-analyze:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build and Analyze Solution
        run: >
          msbuild ClipboardToFile.sln 
          -p:Configuration=Release 
          -p:Platform=x64 
          -p:RunCodeAnalysis=true 
          -p:CodeAnalysisTreatWarningsAsErrors=true